# {dotfiles}/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "Code/dotfiles"

[settings]
prehooks = [
  "mkdir -p ~/.sheldon",
  "mkdir -p ~/.config/bat",
  "mkdir -p ~/.local/bin",
]
# default vars
vars = [ "vars-home.toml" ]

[settings.dots]

# A dot entry representing a symlink
#   `source` is relative to `dotfiles_dir`
#   `target` shall be relative to $HOME directory or absolute

asdfrc = { source = "asdfrc", target = ".asdfrc" }
bat = { source = "bat", target = ".config/bat/config" }
gemrc = { source = "gemrc", target = ".gemrc" }
gitconfig = { source = "gitconfig", target = ".gitconfig" }
ripgrep = { source = "ripgreprc", target = ".ripgreprc" }
sheldon = { source = "sheldon-plugins.toml", target = ".sheldon/plugins.toml" }
starship = { source = "starship.toml", target = ".config/starship.toml" }
zshdir = { source = "zsh_dir", target = ".zsh" }
zshenv = { source = "zshenv", target = ".zshenv" }
lessfilter = { source = "bin/lessfilter", target = ".local/bin/lessfilter" }
inputrc = { source = "inputrc", target = ".inputrc" }

[profiles.work]
vars = [ "vars-work.toml" ]

