#! /usr/bin/env sh
# this is a example of .lessfilter, you can change it

mime=$(file -bL --mime-type "$1")
category=${mime%%/*}

if [ -d "$1" ]; then
	exa --git -hl --color=always --icons "$1"
elif [ "$category" = text ]; then
	bat --color=always "$1"
else
	cat "$1" | bat --color=always
fi
