# ~/.config/starship.toml

format = "$gcloud $kubernetes\n$time <$username@$hostname:$directory$git_branch$git_status $status > "

# Disable the blank line at the start of the prompt
add_newline = false

[time]
disabled = false
time_format = "%R"
format = "[$time](none)"

[username]
disabled = false
show_always = true
format = "[$user](cyan)"

[hostname]
disabled = false
ssh_only = false
format = "[$hostname](cyan)"

[directory]
disabled = false
truncate_to_repo = true
use_logical_path = true
format = "[$path](bold blue)"

[status]
disabled = false
symbol = "[\\$](red)"
success_symbol = "[\\$](green)"
format = "[$symbol](none)"
map_symbol = false

[git_branch]
disabled = false
symbol = "?"
truncation_symbol = ""
ignore_branches = []
format = "[\\($branch\\)](green)"

[git_status]
disabled = false
style = "yellow"
up_to_date = "!"
format = "[\\($all_status\\)]($style)"

[gcloud]
format = '[$account(\($project\)) -](dimmed cyan)'
disabled = false

[kubernetes]
format = '[kctx:$context, kns:$namespace](dimmed cyan)'
disabled = false

[kubernetes.context_aliases]
"teleport.withpersona-teleport.com-persona-web-production-us-central1" = "prod-us"
"teleport.withpersona-teleport.com-persona-web-production-europe-west3" = "prod-eu"

"teleport.withpersona-teleport.com-persona-web-staging-us-central1" = "staging-us"
"teleport.withpersona-teleport.com-persona-web-staging-europe-west3" = "staging-eu"
