# ~/.config/k9s/config.yaml

k9s:
  liveViewAutoRefresh: true
  refreshRate: 1
  maxConnRetry: 15
  # Specifies if modification commands like delete/kill/edit are disabled. Default is false
  # If set to true, there's no cli flag to enable read/write
  readOnly: false
  noExitOnCtrlC: false
  ui:
    crumbsless: false
    enableMouse: false
    headless: false
    logoless: true
    noIcons: false
    reactive: true
    skin: default
  skipLatestRevCheck: true
  disablePodCounting: false
  imageScans:
    enable: false
  logger:
    buffer: 10000
    showTime: false
    sinceSeconds: 600
    tail: 5000
    textWrap: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
