#!/bin/bash
set -o errtrace
set -o errexit
set -o nounset
set -o pipefail

# Update homebrew
if [[ -x $(command -v brew) ]]; then
  echo "=> brew: running update"
  brew update

  echo "=> brew: running upgrade"
  brew upgrade

  echo "=> brew: running cleanup"
  brew cleanup
fi

# Check for macos updates
if [[ -x $(command -v softwareupdate) ]]; then
  echo "=> softwareupdate: installing macOS software updates"
  softwareupdate  softwareupdate --all --install --force --verbose
fi

# Check for available mac app store upgrades, if `mas` is installed
if [[ -x $(command -v mas) ]]; then
  echo "=> mas: checking for outdated apps"
  mas outdated

  # TODO someday: only run this if there are outdated apps from the previous step
  # does mas exit with something other than 0 on outdated apps?
  # 13:01 <nick@arcadia:chezmoi(master)(✘?) $ > mas outdated ; echo $?
  # 0

  echo "=> mas: upgrading apps"
  mas upgrade
fi

# Update mise plugins and tools
if [[ -x $(command -v mise) ]]; then
  echo "=> mise: updating all plugins"
  mise plugin update > /dev/null 2>&1
  echo "=> mise: plugins updated"

  echo "=> mise: updating all tools"
  mise up -y
  echo "=> mise: tools updated"
fi

### Dump some zsh completions into the homebrew dir for autoloads
### prevents having to load the completions on zsh shell startup.

# 1pw cli
if [[ -x $(command -v op) ]]; then
  op completion zsh > $(brew --prefix)/share/zsh/site-functions/_op
fi

# docker cli
if [[ -x $(command -v docker) ]]; then
  docker completion zsh > $(brew --prefix)/share/zsh/site-functions/_docker
fi

# orb cli
if [[ -x $(command -v orb) ]]; then
  orb completion zsh > $(brew --prefix)/share/zsh/site-functions/_orb
fi
