# ~/.config/mise/config.toml
# See https://github.com/jdx/mise/blob/main/README.md for docs

always_keep_download                  = false
always_keep_install                   = false
asdf_compat                           = false
disable_default_shorthands            = false
experimental                          = false
jobs                                  = 6
legacy_version_file                   = true
plugin_autoupdate_last_check_duration = '1 week'
raw                                   = false
verbose                               = false
