# ~/.config/mise/config.toml
# See https://github.com/jdx/mise/blob/main/README.md for docs

min_version = "2024.8.1"

[tools]
ruby = "latest"
go = "latest"
terraform = "latest"
gcloud = "latest"

[settings]
experimental = true
