# ~/.config/mise/config.toml
# See https://github.com/jdx/mise/blob/main/README.md for docs

min_version = "2024.1.1"

[tools]
gcloud = "latest"
go = "latest"
ruby = "latest"
rust = "latest"
terraform = "latest"
