# ~/.config/mise/config.toml
# See https://github.com/jdx/mise/blob/main/README.md for docs

[settings]
legacy_version_file                   = true
always_keep_download                  = false
plugin_autoupdate_last_check_duration = 0
verbose                               = false
asdf_compat                           = false
jobs                                  = 6
raw                                   = false
disable_default_shorthands            = false
experimental                          = false
